package tokeneyes

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sync"
	"testing"
	"time"
)

func TestCollectorIgnoreBinaryGeneratedSymlinkAndOrdering(t *testing.T) {
	root := t.TempDir()
	write := func(name, value string) {
		t.Helper()
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(value), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("z.go", "package z")
	write("a.txt", "alpha\r\n")
	write("ignored.txt", "secret")
	write("generated.go", "// Code generated by test. DO NOT EDIT.\npackage generated")
	write("vendor/dependency.go", "package dependency")
	write(".tokeneyesignore", "ignored.txt\n")
	if err := os.WriteFile(filepath.Join(root, "binary.dat"), []byte{0, 1, 2}, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(root, "a.txt"), filepath.Join(root, "link.txt")); err != nil {
		t.Fatal(err)
	}

	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root})
	if err != nil {
		t.Fatal(err)
	}
	var labels []string
	for _, s := range got.Sources {
		labels = append(labels, s.Label)
	}
	want := []string{".tokeneyesignore", "a.txt", "z.go"}
	if !reflect.DeepEqual(labels, want) {
		t.Fatalf("labels=%v, want %v", labels, want)
	}
	if string(got.Sources[1].Content) != "alpha\n" {
		t.Fatalf("text was not normalized: %q", got.Sources[1].Content)
	}
}

func TestCollectorMarksLimitsIncomplete(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "large.txt"), []byte("0123456789"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, MaxFileBytes: 5, MaxTotalBytes: 100})
	if err != nil {
		t.Fatal(err)
	}
	if !got.Incomplete || len(got.Sources) != 0 || len(got.Warnings) == 0 {
		t.Fatalf("limit result=%+v", got)
	}
}

func TestCollectorPlanPreset(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "plan.md"), []byte("# plan"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "other.md"), []byte("other"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, Preset: "plan"})
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Sources) != 1 || got.Sources[0].Path != "plan.md" {
		t.Fatalf("unexpected plan sources: %+v", got.Sources)
	}
}

func TestCollectorWorkersPreserveDeterministicResults(t *testing.T) {
	root := t.TempDir()
	files := map[string][]byte{
		"a.txt":        []byte("alpha\r\n"),
		"b.bin":        {0, 1, 2},
		"generated.go": []byte("// Code generated by test. DO NOT EDIT.\npackage generated"),
		"report.pdf":   []byte("%PDF-1.4\n1 0 obj << /Type /Page /MediaBox [0 0 612 792] >> stream\nBT (hello pdf) Tj ET\nendstream\nendobj\n%%EOF"),
		"z.txt":        []byte("omega"),
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(root, name), content, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.Symlink(filepath.Join(root, "a.txt"), filepath.Join(root, "link.txt")); err != nil {
		t.Fatal(err)
	}
	paths := []string{"z.txt", "report.pdf", "link.txt", "generated.go", "b.bin", "a.txt", "a.txt"}
	base := CollectRequest{Root: root, Paths: paths, MaxTotalBytes: 256, MaxMediaCount: 1, Workers: 1}
	want, err := NewFileCollector().Collect(context.Background(), base)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 20; i++ {
		request := base
		request.Workers = 8
		got, err := NewFileCollector().Collect(context.Background(), request)
		if err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("parallel result differs on run %d:\ngot  %+v\nwant %+v", i, got, want)
		}
	}
}

func TestCollectorWorkersPreserveOrderedLimits(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"a.txt", "b.txt", "c.txt"} {
		if err := os.WriteFile(filepath.Join(root, name), []byte("1234"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	one, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, MaxTotalBytes: 7, Workers: 1})
	if err != nil {
		t.Fatal(err)
	}
	many, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, MaxTotalBytes: 7, Workers: 8})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(many, one) {
		t.Fatalf("parallel limits differ:\nmany %+v\none  %+v", many, one)
	}
	if len(many.Sources) != 1 || many.Sources[0].Path != "a.txt" || len(many.Warnings) != 2 {
		t.Fatalf("unexpected ordered limit result: %+v", many)
	}
}

func TestProcessCandidatesIsConcurrentAndCommitsInOrder(t *testing.T) {
	candidates := make([]fileCandidate, 4)
	for i := range candidates {
		candidates[i] = fileCandidate{sequence: i, eventIndex: i, rel: fmt.Sprintf("%d.txt", i), size: 1}
	}
	started := make(chan struct{}, len(candidates))
	release := make(chan struct{})
	var releaseOnce sync.Once
	prepare := func(candidate fileCandidate) preparedFile {
		started <- struct{}{}
		<-release
		return preparedFile{candidate: candidate, content: []byte("x")}
	}
	var committed []string
	done := make(chan error, 1)
	go func() {
		done <- processCandidates(context.Background(), candidates, 4, CollectRequest{MaxFileBytes: 10, MaxMediaBytes: 10, MaxTotalBytes: 10}, &Collection{}, prepare, func(result preparedFile) {
			committed = append(committed, result.candidate.rel)
		})
	}()
	for range candidates {
		select {
		case <-started:
		case <-time.After(2 * time.Second):
			releaseOnce.Do(func() { close(release) })
			t.Fatal("workers did not start concurrently")
		}
	}
	releaseOnce.Do(func() { close(release) })
	if err := <-done; err != nil {
		t.Fatal(err)
	}
	want := []string{"0.txt", "1.txt", "2.txt", "3.txt"}
	if !reflect.DeepEqual(committed, want) {
		t.Fatalf("commit order=%v, want %v", committed, want)
	}
}

func TestCollectorHonorsCanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := NewFileCollector().Collect(ctx, CollectRequest{Root: t.TempDir(), Workers: 4})
	if err != context.Canceled {
		t.Fatalf("error=%v, want context.Canceled", err)
	}
}

func BenchmarkCollectorTracked(b *testing.B) {
	root := b.TempDir()
	for i := 0; i < 2_000; i++ {
		name := filepath.Join(root, fmt.Sprintf("file-%04d.txt", i))
		if err := os.WriteFile(name, []byte("package benchmark\nvar payload = \"tokeneyes collector benchmark\"\n"), 0o600); err != nil {
			b.Fatal(err)
		}
	}
	for _, args := range [][]string{{"init", "-q"}, {"add", "."}} {
		cmd := exec.Command("git", append([]string{"-C", root}, args...)...)
		if output, err := cmd.CombinedOutput(); err != nil {
			b.Fatalf("git %v: %v: %s", args, err, output)
		}
	}
	benchmarkCollectorWorkerCounts(b, CollectRequest{Root: root, Preset: "tracked"})
}

func BenchmarkCollectorLargeText(b *testing.B) {
	root := b.TempDir()
	payload := bytes.Repeat([]byte("tokeneyes collector benchmark\n"), 16_384)
	for i := 0; i < 32; i++ {
		name := filepath.Join(root, fmt.Sprintf("large-%02d.txt", i))
		if err := os.WriteFile(name, payload, 0o600); err != nil {
			b.Fatal(err)
		}
	}
	benchmarkCollectorWorkerCounts(b, CollectRequest{Root: root})
}

func BenchmarkCollectorMixedMedia(b *testing.B) {
	root := b.TempDir()
	pdf := []byte("%PDF-1.4\n1 0 obj << /Type /Page /MediaBox [0 0 612 792] >> stream\nBT (hello pdf) Tj ET\nendstream\nendobj\n%%EOF")
	docx := fixtureOffice("word/document.xml", `<w:document xmlns:w="w"><w:body><w:p><w:r><w:t>Benchmark</w:t></w:r></w:p></w:body></w:document>`)
	wav := fixtureWAV(8_000, 1, 8_000)
	for i := 0; i < 24; i++ {
		fixtures := map[string][]byte{
			fmt.Sprintf("document-%02d.pdf", i): pdf,
			fmt.Sprintf("notes-%02d.docx", i):   docx,
			fmt.Sprintf("sound-%02d.wav", i):    wav,
		}
		for name, content := range fixtures {
			if err := os.WriteFile(filepath.Join(root, name), content, 0o600); err != nil {
				b.Fatal(err)
			}
		}
	}
	benchmarkCollectorWorkerCounts(b, CollectRequest{Root: root})
}

func benchmarkCollectorWorkerCounts(b *testing.B, request CollectRequest) {
	b.Helper()
	for _, workers := range []int{1, 2, 4, 8} {
		b.Run(fmt.Sprintf("workers-%d", workers), func(b *testing.B) {
			b.ReportAllocs()
			for i := 0; i < b.N; i++ {
				request.Workers = workers
				if _, err := NewFileCollector().Collect(context.Background(), request); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}
