package tokeneyes

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestCollectorIgnoreBinaryGeneratedSymlinkAndOrdering(t *testing.T) {
	root := t.TempDir()
	write := func(name, value string) {
		t.Helper()
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(value), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("z.go", "package z")
	write("a.txt", "alpha\r\n")
	write("ignored.txt", "secret")
	write("generated.go", "// Code generated by test. DO NOT EDIT.\npackage generated")
	write("vendor/dependency.go", "package dependency")
	write(".tokeneyesignore", "ignored.txt\n")
	if err := os.WriteFile(filepath.Join(root, "binary.dat"), []byte{0, 1, 2}, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(root, "a.txt"), filepath.Join(root, "link.txt")); err != nil {
		t.Fatal(err)
	}

	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root})
	if err != nil {
		t.Fatal(err)
	}
	var labels []string
	for _, s := range got.Sources {
		labels = append(labels, s.Label)
	}
	want := []string{".tokeneyesignore", "a.txt", "z.go"}
	if !reflect.DeepEqual(labels, want) {
		t.Fatalf("labels=%v, want %v", labels, want)
	}
	if string(got.Sources[1].Content) != "alpha\n" {
		t.Fatalf("text was not normalized: %q", got.Sources[1].Content)
	}
}

func TestCollectorMarksLimitsIncomplete(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "large.txt"), []byte("0123456789"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, MaxFileBytes: 5, MaxTotalBytes: 100})
	if err != nil {
		t.Fatal(err)
	}
	if !got.Incomplete || len(got.Sources) != 0 || len(got.Warnings) == 0 {
		t.Fatalf("limit result=%+v", got)
	}
}

func TestCollectorPlanPreset(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "plan.md"), []byte("# plan"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "other.md"), []byte("other"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := NewFileCollector().Collect(context.Background(), CollectRequest{Root: root, Preset: "plan"})
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Sources) != 1 || got.Sources[0].Path != "plan.md" {
		t.Fatalf("unexpected plan sources: %+v", got.Sources)
	}
}
